# Generated by Django 6.0.6 on 2026-06-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('expiry_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images')),
            ],
        ),
    ]
