# Generated by Django 6.0.6 on 2026-06-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_fooditem_create_at_fooditem_updated_at_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
