# Generated by Django 6.0.6 on 2026-06-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_activity_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
