# Generated by Django 6.0.6 on 2026-06-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_fooditem_discounted_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
