# Generated by Django 6.0.6 on 2026-06-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_fooditem_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='quantity',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
    ]
