# Generated by Django 6.0.6 on 2026-06-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_quantity_fooditem_stock_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='FoodItems/'),
        ),
    ]
